name: StockExchange
main: me.ChrizC.stockexchange.StockExchange
version: 1.7
author: ChrizC
description: StockExchange allows your users to trade in fictional stocks, making a profit in your in-game economy!
commands:
  stocks:
    description: Interact with stocks.
    usage: <command> <top5|add|remove|increase|decrease|lookup|buy|sell|limit>
    aliases:
      - market
      - stock
website: http://chrizc.co.uk/index.php?url=plugins